parameters:
    elephantly.mjml.class: Elephantly\MjmlBundle\Compiler\MjmlCompiler
services:
    elephantly.mjml:
        class: %elephantly.mjml.class%
        arguments: ["@twig.loader"]

    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }
